# functions for interacting with cellpose processed data
import os

import numpy as np
from matplotlib import pyplot as plt

from packerlabimaging.main.subcore import ImagingMetadata

from packerlabimaging.main.core import SingleImage
from packerlabimaging.plotting._utils import _add_scalebar


class CellposeImg(SingleImage):
    def __init__(self, dataPath: str, cellpose_npy_path, imparams: ImagingMetadata, saveDir: str, expID: str = '',
                 **kwargs):
        super().__init__(dataPath=dataPath, imparams=imparams, **kwargs)
        if not os.path.exists(cellpose_npy_path):
            raise FileNotFoundError(f'cellpose npy file not found from path: {cellpose_npy_path}')
        self.cellpose_npy_path = cellpose_npy_path

        self.expID = expID
        self.saveDir = saveDir
        self.roi_areas: dict = {}  #: dict containing coordinates of the whole masks generated by cellpose for each ROI
        self.roi_outlines: dict = {}  #: dict containing coordinates of the outlines generated by cellpose for each ROI
        self.masks: np.ndarray = np.empty(shape=[imparams.frame_x,
                                                 imparams.frame_y])  #: numpy array of ROIs masks, ROI # is allocated at the appropriate coordinate

    @property
    def trial_id(self):
        """
TODO fill explanation and add parameters
        :return:
        """
        return f"{self.expID} {self.imgID}"

    @property
    def roi_ids(self):
        """
TODO fill explanation and add parameters
        :return:
        """
        return [*self.roi_areas]

    @classmethod
    def load_cellpose(cls, dataPath: str, cellpose_npy_path, imparams: ImagingMetadata, saveDir: str, expID: str = '',
                      **kwargs):
        """
        Alternate constructor.
        import and load array coords from cellpose generated ROI masks for red channel interneurons.
        TODO add parameters
        :param dataPath:
        :param cellpose_npy_path:
        :param imparams:
        :param saveDir:
        :param expID:
        :param kwargs: """

        cellpose = cls(dataPath=dataPath, cellpose_npy_path=cellpose_npy_path, imparams=imparams, saveDir=saveDir,
                       expID=expID)

        # find all paths with '_seg.npy'
        npy_path = cellpose.cellpose_npy_path

        dat = np.load(npy_path, allow_pickle=True).item()
        rois = np.unique(dat['masks'])[1:]
        outlines = {}
        roi_areas = {}
        for i in rois:
            roi_areas[i] = np.where(dat['masks'] == i)
            outlines[i] = np.where(dat['outlines'] == i)

        cellpose.roi_outlines = outlines
        cellpose.roi_areas = roi_areas
        cellpose.masks = dat['masks']


    def plot_img(self, roi_labels=True, **kwargs):
        """
TODO fill explanation and add parameters
        :param roi_labels:
        :param kwargs:
        """
        fig, ax = plt.subplots(figsize=(6, 6))
        ax.imshow(self.data, cmap='hot')

        if roi_labels:
            # add labels of ROI numbers:
            for roi in self.roi_ids:
                # roi = self.roi_ids[0]
                coord = (int(np.mean(self.roi_areas[roi][0])),
                         int(np.mean(self.roi_areas[roi][1])))
                ax.text(x=coord[1], y=coord[0], s=f'{roi}', fontweight='bold', va='top', color='green', size='x-small')

        ax.set_title(f'{self.trial_id}')

        if 'scalebar_um' in kwargs and 'trialobj' in kwargs:
            _add_scalebar(ax=ax, **kwargs)

        fig.show()

    def plot_rois(self, roi_labels=True, **kwargs):
        """
TODO fill explanation and add parameters
        :param roi_labels:
        :param kwargs:
        """
        fig, ax = plt.subplots(figsize=(6, 6))
        ax.imshow(self.data, cmap='hot')
        ax.imshow(self.masks, cmap='hot', vmin=0, vmax=1)

        if roi_labels:
            # add labels of ROI numbers:
            for roi in self.roi_ids:
                # roi = self.roi_ids[0]
                coord = (int(np.mean(self.roi_areas[roi][0])),
                         int(np.mean(self.roi_areas[roi][1])))
                ax.text(x=coord[1], y=coord[0], s=f'{roi}', fontweight='bold', va='top', color='green', size='x-small')

        ax.set_title(f'{self.trial_id}')
        if 'scalebar_um' in kwargs and 'trialobj' in kwargs:
            _add_scalebar(ax=ax, **kwargs)

        fig.show()
